// ====== 作者数据 ======
const authors = [
  { id: 1, name: 'MiaoKa', avatar: 'https://picsum.photos/seed/a1/150/150', models: 12 },
  { id: 2, name: 'EauDeNoire', avatar: 'https://picsum.photos/seed/a2/150/150', models: 8 },
  { id: 3, name: 'Cyberdelia', avatar: 'https://picsum.photos/seed/a3/150/150', models: 5 },
  { id: 4, name: 'phinjo', avatar: 'https://picsum.photos/seed/a4/150/150', models: 6 },
  { id: 5, name: 'Hoseki', avatar: 'https://picsum.photos/seed/a5/150/150', models: 3 },
  { id: 6, name: 'AiMetatron', avatar: 'https://picsum.photos/seed/a6/150/150', models: 7 },
  { id: 7, name: 'Zoropaton', avatar: 'https://picsum.photos/seed/a7/150/150', models: 10 },
  { id: 8, name: 'GBRX', avatar: 'https://picsum.photos/seed/a8/150/150', models: 4 },
  { id: 9, name: 'VelvetS', avatar: 'https://picsum.photos/seed/a9/150/150', models: 6 },
  { id: 10, name: 'freckledvixon', avatar: 'https://picsum.photos/seed/a10/150/150', models: 3 },
  { id: 11, name: 'Danrisi', avatar: 'https://picsum.photos/seed/a11/150/150', models: 2 },
  { id: 12, name: 'UmeAiRT', avatar: 'https://picsum.photos/seed/a12/150/150', models: 8 },
];

// ====== 模型数据 ======
const models = [
  {
    id: 1,
    name: 'MiaoMiao Harem',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['SD 1.5'],
    author: { id: 1, name: 'MIAOKA' },
    cover: 'https://picsum.photos/seed/m1/600/800',
    version: 'v3.0',
    downloads: 3920000,
    likes: 9300,
    rating: 4.8,
    description: '高质量动漫风格大模型，擅长角色立绘和插画创作，支持多种画风和角色类型。',
    tags: ['动漫', '角色', '插画', 'NSFW'],
    updated: '2026-06-20',
    sampleImages: Array.from({ length: 12 }, (_, i) =>
      `https://picsum.photos/seed/m1-s${i}/800/1200`
    ),
    fileSize: '7.2 GB',
    triggerWords: '',
  },
  {
    id: 2,
    name: 'RedCraft | 红潮',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['SDXL'],
    author: { id: 6, name: 'AiMetatron' },
    cover: 'https://picsum.photos/seed/m2/600/800',
    version: 'v2.1',
    downloads: 857000,
    likes: 9100,
    rating: 4.6,
    description: '红潮系列大模型，专注人物写真和半写实风格，色彩浓郁富有电影感。',
    tags: ['写实', '人物', '电影感', 'NSFW'],
    updated: '2026-06-22',
    sampleImages: Array.from({ length: 10 }, (_, i) =>
      `https://picsum.photos/seed/m2-s${i}/800/1200`
    ),
    fileSize: '6.8 GB',
    triggerWords: 'redcraft',
  },
  {
    id: 3,
    name: 'Hands XL + SD 1.5',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['SDXL', 'SD 1.5', 'Flux', 'Pony', 'Illustrious'],
    author: { id: 2, name: 'EauDeNoire' },
    cover: 'https://picsum.photos/seed/m3/600/800',
    version: 'v1.3',
    downloads: 291600,
    likes: 6900,
    rating: 4.9,
    description: '专业手部修复 LoRA，大幅改善 AI 生成图像中的手部细节，支持多种底模。',
    tags: ['手部', '修复', '细节', '工具'],
    updated: '2026-06-10',
    sampleImages: Array.from({ length: 8 }, (_, i) =>
      `https://picsum.photos/seed/m3-s${i}/800/1200`
    ),
    fileSize: '144 MB',
    triggerWords: 'perfect hands',
  },
  {
    id: 4,
    name: "Velvet's Mythic Fantasy Styles",
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['Flux', 'Pony', 'Illustrious', 'Anima'],
    author: { id: 9, name: 'VelvetS' },
    cover: 'https://picsum.photos/seed/m4/600/800',
    version: 'v2.0',
    downloads: 213400,
    likes: 7000,
    rating: 4.7,
    description: '神话幻想风格 LoRA，为你的角色和场景增添史诗般的幻想氛围。',
    tags: ['幻想', '神话', '风格', '史诗'],
    updated: '2026-06-25',
    sampleImages: Array.from({ length: 10 }, (_, i) =>
      `https://picsum.photos/seed/m4-s${i}/800/1200`
    ),
    fileSize: '198 MB',
    triggerWords: 'mythic fantasy',
  },
  {
    id: 5,
    name: 'Realistic Skin Texture style',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['SDXL', 'SD 1.5', 'Flux', 'Pony', 'Illustrious'],
    author: { id: 2, name: 'EauDeNoire' },
    cover: 'https://picsum.photos/seed/m5/600/800',
    version: 'v1.2',
    downloads: 256300,
    likes: 7200,
    rating: 4.9,
    description: '超写实皮肤纹理 LoRA，增强皮肤的毛孔、血管、光影等细节真实感。',
    tags: ['写实', '皮肤', '纹理', '细节'],
    updated: '2026-06-15',
    sampleImages: Array.from({ length: 8 }, (_, i) =>
      `https://picsum.photos/seed/m5-s${i}/800/1200`
    ),
    fileSize: '175 MB',
    triggerWords: 'detailed skin texture',
  },
  {
    id: 6,
    name: 'Hoseki - LustrousMix',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['Anima'],
    author: { id: 5, name: 'Hoseki' },
    cover: 'https://picsum.photos/seed/m6/600/800',
    version: 'v1.0',
    downloads: 37400,
    likes: 6500,
    rating: 4.5,
    description: '基于 Anima 架构的光泽混合大模型，擅长柔和光影和唯美人像。',
    tags: ['唯美', '光影', '人像', '柔和'],
    updated: '2026-06-18',
    sampleImages: Array.from({ length: 10 }, (_, i) =>
      `https://picsum.photos/seed/m6-s${i}/800/1200`
    ),
    fileSize: '5.4 GB',
    triggerWords: '',
  },
  {
    id: 7,
    name: 'CyberRealistic Pony',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['Pony'],
    author: { id: 3, name: 'Cyberdelia' },
    cover: 'https://picsum.photos/seed/m7/600/800',
    version: 'v3.2',
    downloads: 31200,
    likes: 3400,
    rating: 4.4,
    description: '赛博写实风格大模型，融合科技感与真实感，适合科幻和赛博朋克题材。',
    tags: ['赛博朋克', '科幻', '写实', '科技'],
    updated: '2026-06-08',
    sampleImages: Array.from({ length: 12 }, (_, i) =>
      `https://picsum.photos/seed/m7-s${i}/800/1200`
    ),
    fileSize: '6.2 GB',
    triggerWords: 'cyberrealistic',
  },
  {
    id: 8,
    name: 'Ri-mix | Illustrious + Anima',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['Illustrious', 'Anima'],
    author: { id: 4, name: 'phinjo' },
    cover: 'https://picsum.photos/seed/m8/600/800',
    version: 'v2.0',
    downloads: 40700,
    likes: 5000,
    rating: 4.6,
    description: '混合 Illustrious 和 Anima 架构的融合大模型，兼具双方优势。',
    tags: ['混合', '动漫', '厚涂'],
    updated: '2026-06-12',
    sampleImages: Array.from({ length: 10 }, (_, i) =>
      `https://picsum.photos/seed/m8-s${i}/800/1200`
    ),
    fileSize: '5.8 GB',
    triggerWords: '',
  },
  {
    id: 9,
    name: "Vixon's Anima/Pony Styles - Gothic Neon",
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['Anima', 'Pony'],
    author: { id: 10, name: 'freckledvixon' },
    cover: 'https://picsum.photos/seed/m9/600/800',
    version: 'v1.1',
    downloads: 103900,
    likes: 3100,
    rating: 4.3,
    description: '哥特霓虹风格 LoRA，为角色赋予暗黑又充满活力的霓虹色彩。',
    tags: ['哥特', '霓虹', '暗黑', '风格'],
    updated: '2026-06-05',
    sampleImages: Array.from({ length: 8 }, (_, i) =>
      `https://picsum.photos/seed/m9-s${i}/800/1200`
    ),
    fileSize: '152 MB',
    triggerWords: 'gothic neon',
  },
  {
    id: 10,
    name: 'HomoSimile XL',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['SDXL', 'Pony', 'Illustrious'],
    author: { id: 13, name: 'Kairen92' },
    cover: 'https://picsum.photos/seed/m10/600/800',
    version: 'v1.0',
    downloads: 33300,
    likes: 6200,
    rating: 4.5,
    description: '多底模兼容大模型，支持 SDXL/Pony/Illustrious 多种推理引擎。',
    tags: ['多平台', '兼容', '通用'],
    updated: '2026-06-01',
    sampleImages: Array.from({ length: 12 }, (_, i) =>
      `https://picsum.photos/seed/m10-s${i}/800/1200`
    ),
    fileSize: '7.0 GB',
    triggerWords: '',
  },
  {
    id: 11,
    name: 'Niji semi realism',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['SDXL'],
    author: { id: 7, name: 'Zoropaton' },
    cover: 'https://picsum.photos/seed/m11/600/800',
    version: 'v1.5',
    downloads: 41800,
    likes: 5900,
    rating: 4.6,
    description: '二次元半写实风格 LoRA，在二次元和写实之间找到完美平衡。',
    tags: ['二次元', '半写实', '平衡'],
    updated: '2026-06-24',
    sampleImages: Array.from({ length: 10 }, (_, i) =>
      `https://picsum.photos/seed/m11-s${i}/800/1200`
    ),
    fileSize: '168 MB',
    triggerWords: 'niji semi realism',
  },
  {
    id: 12,
    name: '[PVC Style] Movable figure model',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['SD 1.5'],
    author: { id: 1, name: 'MIAOKA' },
    cover: 'https://picsum.photos/seed/m12/600/800',
    version: 'v2.0',
    downloads: 2700000,
    likes: 5600,
    rating: 4.7,
    description: 'PVC 手办风格大模型，生成的人物如同精致的手办摆件，质感逼真。',
    tags: ['手办', 'PVC', '质感', '模型'],
    updated: '2026-06-14',
    sampleImages: Array.from({ length: 12 }, (_, i) =>
      `https://picsum.photos/seed/m12-s${i}/800/1200`
    ),
    fileSize: '5.6 GB',
    triggerWords: 'pvc figure',
  },
  {
    id: 13,
    name: 'Hyperrealistic LoRA',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['Pony', 'Illustrious', 'Anima'],
    author: { id: 7, name: 'Zoropaton' },
    cover: 'https://picsum.photos/seed/m13/600/800',
    version: 'v2.1',
    downloads: 38400,
    likes: 4800,
    rating: 4.8,
    description: '超写实风格 LoRA，将动漫角色转化为照片级真实人物。',
    tags: ['超写实', '转换', '真实'],
    updated: '2026-06-21',
    sampleImages: Array.from({ length: 8 }, (_, i) =>
      `https://picsum.photos/seed/m13-s${i}/800/1200`
    ),
    fileSize: '189 MB',
    triggerWords: 'hyperrealistic',
  },
  {
    id: 14,
    name: 'GonzaLomo XL/Flux/Pony',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['SDXL', 'Flux', 'Pony'],
    author: { id: 8, name: 'GBRX' },
    cover: 'https://picsum.photos/seed/m14/600/800',
    version: 'v3.0',
    downloads: 101500,
    likes: 3700,
    rating: 4.4,
    description: 'GonzaLomo 多底模版本，跨平台照片风格大师，一键拍出胶片质感。',
    tags: ['胶片', '照片', '复古', 'Lomo'],
    updated: '2026-05-28',
    sampleImages: Array.from({ length: 10 }, (_, i) =>
      `https://picsum.photos/seed/m14-s${i}/800/1200`
    ),
    fileSize: '7.5 GB',
    triggerWords: 'gonzalomo',
  },
  {
    id: 15,
    name: 'Ri-mix - Style LoRA',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['Illustrious', 'Anima'],
    author: { id: 4, name: 'phinjo' },
    cover: 'https://picsum.photos/seed/m15/600/800',
    version: 'v1.0',
    downloads: 46000,
    likes: 4700,
    rating: 4.5,
    description: 'Ri-mix 配套风格 LoRA，强化模型的画风和色彩表现力。',
    tags: ['风格', '增强', '配套'],
    updated: '2026-06-09',
    sampleImages: Array.from({ length: 6 }, (_, i) =>
      `https://picsum.photos/seed/m15-s${i}/800/1200`
    ),
    fileSize: '134 MB',
    triggerWords: 'ri-mix style',
  },
  {
    id: 16,
    name: 'Lenovo UltraReal',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['SDXL'],
    author: { id: 11, name: 'Danrisi' },
    cover: 'https://picsum.photos/seed/m16/600/800',
    version: 'v1.0',
    downloads: 120900,
    likes: 4000,
    rating: 4.3,
    description: '联想超写实 LoRA，增强人物面部细节和皮肤质感，追求极致的真实。',
    tags: ['超写实', '面部', '皮肤'],
    updated: '2026-06-19',
    sampleImages: Array.from({ length: 8 }, (_, i) =>
      `https://picsum.photos/seed/m16-s${i}/800/1200`
    ),
    fileSize: '156 MB',
    triggerWords: 'ultrareal',
  },
  {
    id: 17,
    name: 'Pie - Models',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['Illustrious'],
    author: { id: 14, name: 'mommymia' },
    cover: 'https://picsum.photos/seed/m17/600/800',
    version: 'v1.2',
    downloads: 47900,
    likes: 3100,
    rating: 4.2,
    description: '柔和甜美的动漫大模型，擅长可爱风格和日常场景。',
    tags: ['可爱', '日常', '甜美', '动漫'],
    updated: '2026-06-16',
    sampleImages: Array.from({ length: 10 }, (_, i) =>
      `https://picsum.photos/seed/m17-s${i}/800/1200`
    ),
    fileSize: '5.2 GB',
    triggerWords: '',
  },
  {
    id: 18,
    name: 'EasyNegative',
    type: 'Embedding',
    typeLabel: 'Embedding',
    baseModel: ['SD 1.5', 'SDXL'],
    author: { id: 12, name: 'UmeAiRT' },
    cover: 'https://picsum.photos/seed/m18/600/800',
    version: 'v3.0',
    downloads: 5200000,
    likes: 12500,
    rating: 4.9,
    description: '经典负向 Embedding，一键排除低质量、畸形、水印等常见问题。最常用的文本嵌入之一。',
    tags: ['负向', '质量', '必备', '工具'],
    updated: '2026-03-15',
    sampleImages: Array.from({ length: 4 }, (_, i) =>
      `https://picsum.photos/seed/m18-s${i}/800/1200`
    ),
    fileSize: '32 KB',
    triggerWords: 'easynegative',
  },
  {
    id: 19,
    name: 'bad-hands-5',
    type: 'Embedding',
    typeLabel: 'Embedding',
    baseModel: ['SD 1.5'],
    author: { id: 15, name: 'yesyeah' },
    cover: 'https://picsum.photos/seed/m19/600/800',
    version: 'v5.0',
    downloads: 3800000,
    likes: 9800,
    rating: 4.8,
    description: '专注修复手部问题的 Embedding，放入负向提示词即可显著减少畸形手部。',
    tags: ['手部', '修复', '负向', '必备'],
    updated: '2026-02-20',
    sampleImages: Array.from({ length: 4 }, (_, i) =>
      `https://picsum.photos/seed/m19-s${i}/800/1200`
    ),
    fileSize: '28 KB',
    triggerWords: 'bad-hands-5',
  },
  {
    id: 20,
    name: 'sd-vae-ft-mse',
    type: 'VAE',
    typeLabel: 'VAE',
    baseModel: ['SD 1.5'],
    author: { id: 16, name: 'stabilityai' },
    cover: 'https://picsum.photos/seed/m20/600/800',
    version: 'v1.0',
    downloads: 8500000,
    likes: 18500,
    rating: 4.9,
    description: '官方 MSE 优化 VAE，提升色彩饱和度和画面清晰度，几乎所有 SD 1.5 用户必备。',
    tags: ['VAE', '清晰', '色彩', '必备'],
    updated: '2025-11-01',
    sampleImages: Array.from({ length: 6 }, (_, i) =>
      `https://picsum.photos/seed/m20-s${i}/800/1200`
    ),
    fileSize: '326 MB',
    triggerWords: '',
  },
  {
    id: 21,
    name: 'ClearVAE XL',
    type: 'VAE',
    typeLabel: 'VAE',
    baseModel: ['SDXL'],
    author: { id: 17, name: 'madebyollin' },
    cover: 'https://picsum.photos/seed/m21/600/800',
    version: 'v2.0',
    downloads: 2100000,
    likes: 8700,
    rating: 4.7,
    description: 'SDXL 专用 VAE，优化色彩还原和锐度，解决 SDXL 默认 VAE 偏灰的问题。',
    tags: ['SDXL', 'VAE', '色彩', '锐度'],
    updated: '2026-04-10',
    sampleImages: Array.from({ length: 6 }, (_, i) =>
      `https://picsum.photos/seed/m21-s${i}/800/1200`
    ),
    fileSize: '335 MB',
    triggerWords: '',
  },
  {
    id: 22,
    name: 'negative_hand-negative',
    type: 'Embedding',
    typeLabel: 'Embedding',
    baseModel: ['SD 1.5', 'SDXL'],
    author: { id: 18, name: 'Nerfgun3' },
    cover: 'https://picsum.photos/seed/m22/600/800',
    version: 'v1.0',
    downloads: 1500000,
    likes: 6500,
    rating: 4.6,
    description: '通用手部负向 Embedding，兼容 SD 1.5 和 SDXL，放入负向提示即可。',
    tags: ['手部', '负向', '通用'],
    updated: '2026-01-08',
    sampleImages: Array.from({ length: 4 }, (_, i) =>
      `https://picsum.photos/seed/m22-s${i}/800/1200`
    ),
    fileSize: '30 KB',
    triggerWords: 'negative_hand-neg',
  },
  {
    id: 23,
    name: 'AS-YoungV2',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['SD 1.5'],
    author: { id: 19, name: 'asdwad' },
    cover: 'https://picsum.photos/seed/m23/600/800',
    version: 'v2.0',
    downloads: 580000,
    likes: 8100,
    rating: 4.6,
    description: '年轻化风格 LoRA，让角色看起来更年轻可爱，适合二次元创作。',
    tags: ['年轻', '可爱', '二次元', '风格'],
    updated: '2026-05-30',
    sampleImages: Array.from({ length: 8 }, (_, i) =>
      `https://picsum.photos/seed/m23-s${i}/800/1200`
    ),
    fileSize: '142 MB',
    triggerWords: 'as-youngv2',
  },
  {
    id: 24,
    name: 'WAN2.1 IMG to VIDEO',
    type: 'Workflow',
    typeLabel: '工作流',
    baseModel: ['WAN'],
    author: { id: 12, name: 'UmeAiRT' },
    cover: 'https://picsum.photos/seed/m24/600/800',
    version: 'v1.0',
    downloads: 98700,
    likes: 3200,
    rating: 4.4,
    description: 'WAN2.1 图生视频工作流，一键将静态图片转换为高质量视频。',
    tags: ['视频', '工作流', 'WAN', '转换'],
    updated: '2026-06-23',
    sampleImages: Array.from({ length: 6 }, (_, i) =>
      `https://picsum.photos/seed/m24-s${i}/800/1200`
    ),
    fileSize: '12 MB',
    triggerWords: '',
  },
  {
    id: 25,
    name: '[PVC Style] Movable figure model V2',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['SD 1.5'],
    author: { id: 1, name: 'MIAOKA' },
    cover: 'https://picsum.photos/seed/m25/600/800',
    version: 'v1.0',
    downloads: 180000,
    likes: 4200,
    rating: 4.5,
    description: 'PVC 手办风格 LoRA 版，更轻量，可配合其他大模型使用。',
    tags: ['手办', 'PVC', 'LoRA', '风格'],
    updated: '2026-05-15',
    sampleImages: Array.from({ length: 8 }, (_, i) =>
      `https://picsum.photos/seed/m25-s${i}/800/1200`
    ),
    fileSize: '98 MB',
    triggerWords: 'pvc style',
  },
  {
    id: 26,
    name: 'Pony Diffusion V6 XL',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['SDXL'],
    author: { id: 20, name: 'AstraliteHeart' },
    cover: 'https://picsum.photos/seed/m26/600/800',
    version: 'v6.0',
    downloads: 12500000,
    likes: 28500,
    rating: 4.8,
    description: 'Pony Diffusion 最新版，基于 SDXL 架构的顶级动漫大模型，社区最受欢迎之一。',
    tags: ['动漫', 'SDXL', '顶级', '社区'],
    updated: '2026-06-26',
    sampleImages: Array.from({ length: 16 }, (_, i) =>
      `https://picsum.photos/seed/m26-s${i}/800/1200`
    ),
    fileSize: '6.9 GB',
    triggerWords: '',
  },
  {
    id: 27,
    name: 'Detail Tweaker LoRA',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['SDXL', 'SD 1.5'],
    author: { id: 21, name: 'lykon' },
    cover: 'https://picsum.photos/seed/m27/600/800',
    version: 'v1.0',
    downloads: 420000,
    likes: 6400,
    rating: 4.7,
    description: '细节增强 LoRA，提升图像整体细节密度，让画面更丰富立体。',
    tags: ['细节', '增强', '通用', '工具'],
    updated: '2026-04-22',
    sampleImages: Array.from({ length: 8 }, (_, i) =>
      `https://picsum.photos/seed/m27-s${i}/800/1200`
    ),
    fileSize: '126 MB',
    triggerWords: 'detail tweaker',
  },
  {
    id: 28,
    name: 'Counterfeit-V3.0',
    type: 'Checkpoint',
    typeLabel: '大模型',
    baseModel: ['SD 1.5'],
    author: { id: 22, name: 'gsdf' },
    cover: 'https://picsum.photos/seed/m28/600/800',
    version: 'v3.0',
    downloads: 6800000,
    likes: 15400,
    rating: 4.7,
    description: '经典动漫大模型，以高度还原动漫风格而闻名，社区长期热门模型。',
    tags: ['动漫', '经典', '还原'],
    updated: '2026-03-28',
    sampleImages: Array.from({ length: 12 }, (_, i) =>
      `https://picsum.photos/seed/m28-s${i}/800/1200`
    ),
    fileSize: '4.2 GB',
    triggerWords: '',
  },
  {
    id: 29,
    name: 'Color Adjust',
    type: 'LoRA',
    typeLabel: 'LoRA',
    baseModel: ['SD 1.5', 'SDXL'],
    author: { id: 23, name: 'ColorMaster' },
    cover: 'https://picsum.photos/seed/m29/600/800',
    version: 'v1.1',
    downloads: 95000,
    likes: 2800,
    rating: 4.2,
    description: '色彩调整 LoRA，精确控制画面的色调、饱和度和对比度。',
    tags: ['色彩', '调整', '控制'],
    updated: '2026-05-08',
    sampleImages: Array.from({ length: 6 }, (_, i) =>
      `https://picsum.photos/seed/m29-s${i}/800/1200`
    ),
    fileSize: '88 MB',
    triggerWords: 'color adjust',
  },
  {
    id: 30,
    name: 'sdxl-vae-fp16-fix',
    type: 'VAE',
    typeLabel: 'VAE',
    baseModel: ['SDXL'],
    author: { id: 17, name: 'madebyollin' },
    cover: 'https://picsum.photos/seed/m30/600/800',
    version: 'v1.0',
    downloads: 1800000,
    likes: 7600,
    rating: 4.7,
    description: 'SDXL FP16 优化 VAE，大幅减少显存占用，适合低配置设备。',
    tags: ['SDXL', 'VAE', '优化', '低配'],
    updated: '2026-02-14',
    sampleImages: Array.from({ length: 4 }, (_, i) =>
      `https://picsum.photos/seed/m30-s${i}/800/1200`
    ),
    fileSize: '167 MB',
    triggerWords: '',
  },
];
